### ISSUE TITLE
"Freezing Temperatures" clipping through end of Evidence screen in Evidence Remaining

### ISSUE THREAD

**Issue by cptsofi** [Redseb/phasmophobia-companion#1]
### Following happens when you select _only_ EMF 5 _or_ Spirit Box _or_ Fingerprints _or_ Ghost Orb _or_ Ghost Writing in the Evidence Screen:
<img src="https://user-images.githubusercontent.com/63684534/95677992-c799a780-0bc9-11eb-8b23-399a97c17e24.png" height= "30%" width= "30%">

### _or_ Freezing Temperatures, whilst for Freezing Temperatures its Ghost Writing that clips through.
<img src="https://user-images.githubusercontent.com/63684534/95678269-d719f000-0bcb-11eb-8b8e-7d379a9fa9d3.png" height= "30%" width= "30%">

My phone is: Motorla One Hyper
With a Screen resolution of: 1080x2340px

But I'd assume it's not a phone specific thing.

**Comment by Redseb** [comment]
Good catch! The best solution will probably be to either decrease the fontSize or to reorganize the page. I'll get on it

**Comment by cptsofi** [comment]
> Good catch! The best solution will probably be to either decrease the fontSize or to reorganize the page. I'll get on it

I think decreasing the fontSize should work out just fine!

**Comment by Redseb** [comment]
V.1.3 will have a fixed version of this. Fingers crossed we don't have more responsive design issues!
